/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.questionariotemperamentos;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Giuliano
 */
public class QuestionarioView extends javax.swing.JFrame {

    int resposta1 = 0;
    int resposta2 = 0;
    int resposta3 = 0;
    int resposta4 = 0;
    int respostaMaior = 0;
    int temperamento = 0;

    /**
     * Creates new form QuestionarioView
     */
    public QuestionarioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEnviarTeste = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnresposta1 = new javax.swing.JButton();
        btnresposta2 = new javax.swing.JButton();
        btnresposta3 = new javax.swing.JButton();
        btnresposta4 = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teste de Temperamentos");
        setMinimumSize(new java.awt.Dimension(640, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Source Code Pro", 0, 36)); // NOI18N
        jLabel1.setText("Teste de Temperamentos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 10, 510, 46);

        jLabel2.setText("Escolha na lista as palavras que melhor o descrevem. ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(62, 58, 390, 16);

        jLabel3.setText("Lendo as colunas horizontalmente, circule apenas uma palavra de cada linha.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 90, 480, 20);

        jLabel4.setText("Quando finalizar a lista, clique em \"Obter Resultado\".");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 120, 490, 16);

        btnEnviarTeste.setFont(new java.awt.Font("Source Code Pro Semibold", 0, 36)); // NOI18N
        btnEnviarTeste.setText("Obter Resultado");
        btnEnviarTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarTesteActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviarTeste);
        btnEnviarTeste.setBounds(50, 540, 510, 40);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(146, 140, 0, 0);

        btnresposta1.setFont(new java.awt.Font("Source Code Pro", 0, 24)); // NOI18N
        btnresposta1.setText("1");
        btnresposta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresposta1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnresposta1);
        btnresposta1.setBounds(50, 449, 125, 37);

        btnresposta2.setFont(new java.awt.Font("Source Code Pro", 0, 24)); // NOI18N
        btnresposta2.setText("2");
        btnresposta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresposta2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnresposta2);
        btnresposta2.setBounds(181, 449, 123, 37);

        btnresposta3.setFont(new java.awt.Font("Source Code Pro", 0, 24)); // NOI18N
        btnresposta3.setText("3");
        btnresposta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresposta3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnresposta3);
        btnresposta3.setBounds(310, 449, 113, 37);

        btnresposta4.setFont(new java.awt.Font("Source Code Pro", 0, 24)); // NOI18N
        btnresposta4.setText("4");
        btnresposta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresposta4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnresposta4);
        btnresposta4.setBounds(429, 449, 138, 37);

        btnReiniciar.setFont(new java.awt.Font("Source Code Pro Semibold", 0, 24)); // NOI18N
        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReiniciar);
        btnReiniciar.setBounds(10, 608, 230, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Despreocupado ", "Impulsivo ", "Pessimista", "Cuidadoso"},
                {"Calmo ", "Irrequieto ", "Melancólico ", "Metódico "},
                {"Animado ", "Esquentado ", "Amuado ", "Estável "},
                {"Jovial ", "Ativo ", "Sóbrio ", "Passivo "},
                {"Sociável ", "Excitável ", "Nervoso ", "Pacato "},
                {"Simpático ", "Corado ", "Distante ", "Pensativo "},
                {"Loquaz ", "Agressivo ", "Quieto ", "Calmo "},
                {"Age rápido ", "Um Líder ", "Reservado ", "Controlado "},
                {"Workaholic ", "Convincente ", "Resignado ", "Folgado "},
                {"Tagarela ", "Cheio de energia ", "Triste ", "Plácido "},
                {"Eloquente ", "Extrovertido ", "Desanimado ", "Sem pressa "},
                {"Superficial ", "Turbulento ", "Pensativo ", "Lento "},
                {"Expansivo ", "Impaciente ", "Introspectivo  ", "Implacável "},
                {"Falante ", "Empreendedor ", "Egoísta ", "Comedido "},
                {"Amigável ", "Pioneiro ", "Exigente ", "Tranquilo "},
                {"Adaptável ", "Barulhento ", "Suscetível ", "Ensimesmado "},
                {"Pitoresco ", "Prático ", "Leitor ", "Reservado "},
                {"Brilhante ", "Dramático ", "Lento ", "Sonhador "},
                {"Impaciente ", "Esquecido ", "Tristonho ", "Gosta de rotina "},
                {"Irresponsável ", "Esportivo ", "Taciturno ", "Lento para aprender "},
                {"Não Confiável ", "Competitivo ", "Intelectual ", "Perseverante "},
                {"Fugidio ", "Resistente ", "Boa memória ", "Obstinado "},
                {"Flexível ", "Dominador ", "Observador ", "Tímido "},
                {"Generoso ", "Intolerante ", "Ingrato ", "Constante "},
                {"Levante cedo ", "Obstinado ", "Insatisfeito ", "Sensato "},
                {"Volúvel ", "Irascível ", "Abnegado ", "Indiferente "},
                {"Feliz ", "Audaz ", "Inconsolável ", "Apático "},
                {"Fim", "Fim", "Fim", "Fim"}
            },
            new String [] {
                "Coluna 1", "Coluna 2", "Coluna 3", "Coluna 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable1);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(50, 158, 517, 279);

        lbl1.setText("Contador 1:  0");
        getContentPane().add(lbl1);
        lbl1.setBounds(60, 490, 100, 16);

        lbl2.setText("Contador 2 : 0 ");
        getContentPane().add(lbl2);
        lbl2.setBounds(200, 490, 90, 16);

        lbl3.setText("Contador 3 : 0");
        getContentPane().add(lbl3);
        lbl3.setBounds(330, 490, 90, 16);

        lbl4.setText("Contador 4 :  0");
        getContentPane().add(lbl4);
        lbl4.setBounds(450, 490, 110, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnresposta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresposta1ActionPerformed
        resposta1++;
        lbl1.setText("Contador 1: " + resposta1);
    }//GEN-LAST:event_btnresposta1ActionPerformed

    private void btnresposta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresposta2ActionPerformed
        resposta2++;
        lbl2.setText("Contador 2: " + resposta2);
    }//GEN-LAST:event_btnresposta2ActionPerformed

    private void btnresposta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresposta3ActionPerformed
        resposta3++;
        lbl3.setText("Contador 3: " + resposta3);
    }//GEN-LAST:event_btnresposta3ActionPerformed

    private void btnresposta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresposta4ActionPerformed
        resposta4++;
        lbl4.setText("Contador 4: " + resposta4);
    }//GEN-LAST:event_btnresposta4ActionPerformed

    private void btnEnviarTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarTesteActionPerformed
        respostaMaior = 0;
        temperamento = 0;

        if (resposta1 > respostaMaior) {
            respostaMaior = resposta1;
            temperamento = 1;
        }
        if (resposta2 > respostaMaior) {
            respostaMaior = resposta2;
            temperamento = 2;
        }
        if (resposta3 > respostaMaior) {
            respostaMaior = resposta3;
            temperamento = 3;
        }
        if (resposta4 > respostaMaior) {
            respostaMaior = resposta4;
            temperamento = 4;
        }

        if (temperamento == 1) {
            JOptionPane.showMessageDialog(this, temperamento + " Temperamento Sanguíneo! " + respostaMaior, "Resultado", 1);
        } else if (temperamento == 2) {
            JOptionPane.showMessageDialog(this, temperamento + " Temperamento Colético! " + respostaMaior, "Resultado", 1);
        } else if (temperamento == 3) {
            JOptionPane.showMessageDialog(this, temperamento + " Temperamento Melancólico! " + respostaMaior, "Resultado", 1);
        } else if (temperamento == 4) {
            JOptionPane.showMessageDialog(this, temperamento + " Temperamento Fleumático! " + respostaMaior, "Resultado", 1);
        } else if (temperamento == 0) {
            JOptionPane.showMessageDialog(this, "Total de respostas = " + temperamento + " - " + respostaMaior + " Sem resultado.", "Resultado", 1);
        }
    }//GEN-LAST:event_btnEnviarTesteActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        resposta1 = 0;
        resposta2 = 0;
        resposta3 = 0;
        resposta4 = 0;
        respostaMaior = 0;
        temperamento = 0;
        lbl1.setText("Contador 1: " + resposta1);
        lbl2.setText("Contador 2: " + resposta2);
        lbl2.setText("Contador 3: " + resposta3);
        lbl3.setText("Contador 4: " + resposta4);
    }//GEN-LAST:event_btnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionarioView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionarioView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionarioView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionarioView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarTeste;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnresposta1;
    private javax.swing.JButton btnresposta2;
    private javax.swing.JButton btnresposta3;
    private javax.swing.JButton btnresposta4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    // End of variables declaration//GEN-END:variables
}
