/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.questionariotemperamentos;

import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author Giuliano
 */
public class QuestionarioView extends javax.swing.JFrame {

    int resposta1 = 0;
    int resposta2 = 0;
    int resposta3 = 0;
    int resposta4 = 0;
    int respostaMaior = 0;
    int temperamento = 0;

    /**
     * Creates new form QuestionarioView
     */
    public QuestionarioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEnviarTeste = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnresposta1 = new javax.swing.JButton();
        btnresposta2 = new javax.swing.JButton();
        btnresposta3 = new javax.swing.JButton();
        btnresposta4 = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        btnReiniciar1 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teste de Temperamentos");
        setMinimumSize(new java.awt.Dimension(640, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Source Code Pro", 0, 36)); // NOI18N
        jLabel1.setText("Teste de Temperamentos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 10, 510, 46);

        jLabel2.setText("Escolha na lista as palavras que melhor o descrevem. ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 60, 390, 20);

        jLabel3.setText("Lendo as colunas horizontalmente, circule apenas uma palavra de cada linha.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 80, 480, 20);

        jLabel4.setText("Quando finalizar a lista, clique em \"Obter Resultado\".");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 100, 490, 16);

        btnEnviarTeste.setFont(new java.awt.Font("Source Code Pro Semibold", 0, 36)); // NOI18N
        btnEnviarTeste.setText("Obter Resultado");
        btnEnviarTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarTesteActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviarTeste);
        btnEnviarTeste.setBounds(50, 432, 510, 40);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(146, 140, 0, 0);

        btnresposta1.setFont(new java.awt.Font("Source Code Pro", 0, 24)); // NOI18N
        btnresposta1.setText("1");
        btnresposta1.setFocusPainted(false);
        btnresposta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresposta1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnresposta1);
        btnresposta1.setBounds(50, 360, 125, 37);

        btnresposta2.setFont(new java.awt.Font("Source Code Pro", 0, 24)); // NOI18N
        btnresposta2.setText("2");
        btnresposta2.setFocusPainted(false);
        btnresposta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresposta2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnresposta2);
        btnresposta2.setBounds(180, 360, 123, 37);

        btnresposta3.setFont(new java.awt.Font("Source Code Pro", 0, 24)); // NOI18N
        btnresposta3.setText("3");
        btnresposta3.setFocusPainted(false);
        btnresposta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresposta3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnresposta3);
        btnresposta3.setBounds(310, 360, 113, 37);

        btnresposta4.setFont(new java.awt.Font("Source Code Pro", 0, 24)); // NOI18N
        btnresposta4.setText("4");
        btnresposta4.setFocusPainted(false);
        btnresposta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresposta4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnresposta4);
        btnresposta4.setBounds(430, 360, 130, 37);

        btnReiniciar.setFont(new java.awt.Font("Source Code Pro Semibold", 0, 24)); // NOI18N
        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReiniciar);
        btnReiniciar.setBounds(50, 510, 230, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Despreocupado ", "Impulsivo ", "Pessimista", "Cuidadoso"},
                {"Calmo ", "Irrequieto ", "Melancólico ", "Metódico "},
                {"Animado ", "Esquentado ", "Amuado ", "Estável "},
                {"Jovial ", "Ativo ", "Sóbrio ", "Passivo "},
                {"Sociável ", "Excitável ", "Nervoso ", "Pacato "},
                {"Simpático ", "Corado ", "Distante ", "Pensativo "},
                {"Loquaz ", "Agressivo ", "Quieto ", "Calmo "},
                {"Age rápido ", "Um Líder ", "Reservado ", "Controlado "},
                {"Workaholic ", "Convincente ", "Resignado ", "Folgado "},
                {"Tagarela ", "Cheio de energia ", "Triste ", "Plácido "},
                {"Eloquente ", "Extrovertido ", "Desanimado ", "Sem pressa "},
                {"Superficial ", "Turbulento ", "Pensativo ", "Lento "},
                {"Expansivo ", "Impaciente ", "Introspectivo  ", "Implacável "},
                {"Falante ", "Empreendedor ", "Egoísta ", "Comedido "},
                {"Amigável ", "Pioneiro ", "Exigente ", "Tranquilo "},
                {"Adaptável ", "Barulhento ", "Suscetível ", "Ensimesmado "},
                {"Pitoresco ", "Prático ", "Leitor ", "Reservado "},
                {"Brilhante ", "Dramático ", "Lento ", "Sonhador "},
                {"Impaciente ", "Esquecido ", "Tristonho ", "Gosta de rotina "},
                {"Irresponsável ", "Esportivo ", "Taciturno ", "Lento para aprender "},
                {"Não Confiável ", "Competitivo ", "Intelectual ", "Perseverante "},
                {"Fugidio ", "Resistente ", "Boa memória ", "Obstinado "},
                {"Flexível ", "Dominador ", "Observador ", "Tímido "},
                {"Generoso ", "Intolerante ", "Ingrato ", "Constante "},
                {"Levante cedo ", "Obstinado ", "Insatisfeito ", "Sensato "},
                {"Volúvel ", "Irascível ", "Abnegado ", "Indiferente "},
                {"Feliz ", "Audaz ", "Inconsolável ", "Apático "},
                {"Fim", "Fim", "Fim", "Fim"}
            },
            new String [] {
                "Coluna 1", "Coluna 2", "Coluna 3", "Coluna 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable1);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(50, 170, 510, 180);

        lbl1.setText("Contador 1:  0");
        getContentPane().add(lbl1);
        lbl1.setBounds(60, 400, 100, 16);

        lbl2.setText("Contador 2 : 0 ");
        getContentPane().add(lbl2);
        lbl2.setBounds(200, 400, 90, 16);

        lbl3.setText("Contador 3 : 0");
        getContentPane().add(lbl3);
        lbl3.setBounds(330, 400, 90, 16);

        lbl4.setText("Contador 4 :  0");
        getContentPane().add(lbl4);
        lbl4.setBounds(450, 400, 110, 20);

        btnReiniciar1.setFont(new java.awt.Font("Source Code Pro Semibold", 0, 14)); // NOI18N
        btnReiniciar1.setText("Clique aqui e saiba mais sobre os temperamentos");
        btnReiniciar1.setFocusPainted(false);
        btnReiniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReiniciar1);
        btnReiniciar1.setBounds(50, 130, 510, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnresposta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresposta1ActionPerformed
        resposta1++;
        lbl1.setText("Contador 1: " + resposta1);
    }//GEN-LAST:event_btnresposta1ActionPerformed

    private void btnresposta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresposta2ActionPerformed
        resposta2++;
        lbl2.setText("Contador 2: " + resposta2);
    }//GEN-LAST:event_btnresposta2ActionPerformed

    private void btnresposta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresposta3ActionPerformed
        resposta3++;
        lbl3.setText("Contador 3: " + resposta3);
    }//GEN-LAST:event_btnresposta3ActionPerformed

    private void btnresposta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresposta4ActionPerformed
        resposta4++;
        lbl4.setText("Contador 4: " + resposta4);
    }//GEN-LAST:event_btnresposta4ActionPerformed

    private void btnEnviarTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarTesteActionPerformed
        respostaMaior = 0;
        temperamento = 0;

        if (resposta1 > respostaMaior) {
            respostaMaior = resposta1;
            temperamento = 1;
        }
        if (resposta2 > respostaMaior) {
            respostaMaior = resposta2;
            temperamento = 2;
        }
        if (resposta3 > respostaMaior) {
            respostaMaior = resposta3;
            temperamento = 3;
        }
        if (resposta4 > respostaMaior) {
            respostaMaior = resposta4;
            temperamento = 4;
        }
        
        String resultado1 = "Resultado: O seu temperamento é o Sanguíneo.\n"
                + "\nA pessoa que tem o temperamento sanguíneo é caracterizada por ser mais extrovertida e otimista.\n"
                + "\n"
                + "São pessoas alegres, esperançosas, calorosas, amáveis e simpáticas. De modo geral são explosivas, instáveis emocionalmente, impulsivas e até egoístas.\n"
                + "\n"
                + "Sabe aquele seu amigo que tem uma certa dificuldade de ficar quieto? Que está sempre fazendo uma piada ou que te interrompe sempre que você está falando? Então, essas são características de um sanguíneo ";
        
        String resultado2 = "Resultado: O seu temperamento é o Colérico.\n"
                + "\nPessoas com temperamento colérico são mais explosivas e agressivas do que as demais.\n"
                + "\n"
                + "São pessoas dominadoras, ambiciosas, determinadas, impulsivas, comandam e lideram e são bons planejadores. Em algumas situações são intolerantes, egocêntricos e impacientes. ";
        
        String resultado3 = "Resultado: O seu temperamento é o Melancólico.\n"
                + "\nO temperamento mais profundo é o melancólico. Os melancólicos são sensíveis em suas emoções, são pessoas detalhistas, que gostam de ficar mais quietinhas.\n"
                + "\n"
                + "Possuem dificuldade de expor as suas emoções e sentimentos, são fiéis e desconfiados. São pessoas leais, sensíveis e dedicadas. ";
       
        String resultado4 = "Resultado: O seu temperamento é o Fleumático.\n"
                + "\nSabe aquela pessoa que faz de tudo para evitar um conflito? Então, essa é uma das características de um fleumático.\n"
                + "\n"
                + "São pessoas dóceis, pacíficas, sonhadoras, positivas e disciplinadas. Geralmente essas pessoas são confiáveis e equilibradas. ";

        if (temperamento == 1) {
            JOptionPane.showMessageDialog(this, resultado1, "Resultado", 1);
        } else if (temperamento == 2) {
            JOptionPane.showMessageDialog(this, resultado2, "Resultado", 1);
        } else if (temperamento == 3) {
            JOptionPane.showMessageDialog(this, resultado3, "Resultado", 1);
        } else if (temperamento == 4) {
            JOptionPane.showMessageDialog(this, resultado4, "Resultado", 1);
        } else if (temperamento == 0) {
            JOptionPane.showMessageDialog(this, "Total de respostas = " + temperamento + " - " + respostaMaior + " Sem resultado.", "Resultado", 1);
        }
    }//GEN-LAST:event_btnEnviarTesteActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        resposta1 = 0;
        resposta2 = 0;
        resposta3 = 0;
        resposta4 = 0;
        respostaMaior = 0;
        temperamento = 0;
        lbl1.setText("Contador 1: " + resposta1);
        lbl2.setText("Contador 2: " + resposta2);
        lbl3.setText("Contador 3: " + resposta3);
        lbl4.setText("Contador 4: " + resposta4);
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnReiniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciar1ActionPerformed

        try {
            URI link = new URI("https://www.google.com/search?q=4+temperamentos+sangu%C3%ADneo++col%C3%A9rico+melanc%C3%B3lico+fleum%C3%A1tico&sxsrf=ALiCzsb4I57aHT0BmS7HOFLx3dUZN7KGyw%3A1659926949102&ei=pXnwYqP2Bee55OUP2OqGgAI&ved=0ahUKEwjj3J3hnbb5AhXnHLkGHVi1ASAQ4dUDCA4&uact=5&oq=4+temperamentos+sangu%C3%ADneo++col%C3%A9rico+melanc%C3%B3lico+fleum%C3%A1tico&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECcyCAgAEB4QBxAFMgYIABAeEAg6BwgAEEcQsANKBAhBGABKBAhGGABQnQlYnQlg5ApoAnABeACAAaMBiAGjAZIBAzAuMZgBAKABAcgBCMABAQ&sclient=gws-wiz");
            Desktop.getDesktop().browse(link);
        } catch (Exception erro) {
            System.out.println(erro);
        }    }//GEN-LAST:event_btnReiniciar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionarioView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionarioView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionarioView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionarioView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarTeste;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnReiniciar1;
    private javax.swing.JButton btnresposta1;
    private javax.swing.JButton btnresposta2;
    private javax.swing.JButton btnresposta3;
    private javax.swing.JButton btnresposta4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    // End of variables declaration//GEN-END:variables
}
